// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkQI_fyOIIc2W8ZNR_QfGsWuNPF8CbG30',
    appId: '1:633793611105:web:c734b8acf2de31ff2b3120',
    messagingSenderId: '633793611105',
    projectId: 'asistant-ia',
    authDomain: 'asistant-ia.firebaseapp.com',
    storageBucket: 'asistant-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY03dx4h19wF_FLGptmPhavnoijk-SsnY',
    appId: '1:633793611105:android:c521081ba300069f2b3120',
    messagingSenderId: '633793611105',
    projectId: 'asistant-ia',
    storageBucket: 'asistant-ia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEqzNkgIjnFmg8NuopK5IZJXrzkSPGVkw',
    appId: '1:633793611105:ios:e604bc2461b786622b3120',
    messagingSenderId: '633793611105',
    projectId: 'asistant-ia',
    storageBucket: 'asistant-ia.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEqzNkgIjnFmg8NuopK5IZJXrzkSPGVkw',
    appId: '1:633793611105:ios:e604bc2461b786622b3120',
    messagingSenderId: '633793611105',
    projectId: 'asistant-ia',
    storageBucket: 'asistant-ia.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkQI_fyOIIc2W8ZNR_QfGsWuNPF8CbG30',
    appId: '1:633793611105:web:69a5b6c4578dd5362b3120',
    messagingSenderId: '633793611105',
    projectId: 'asistant-ia',
    authDomain: 'asistant-ia.firebaseapp.com',
    storageBucket: 'asistant-ia.appspot.com',
  );
}
